const version=(nivel,reto,materiales,pasos,condicion,variacion,reflexion)=>({nivel,objetivo:reto,materiales,pasos,condicion,variacion,reflexion,duracion:nivel});
const both=(primaria,secundaria,base)=>({primaria:version(primaria,...base),secundaria:version(secundaria,...base)});
const primary=(nivel,base)=>({primaria:version(nivel,...base)});
const secondary=(nivel,base)=>({secundaria:version(nivel,...base)});

const GUIDE_BASE=[
{id:"agente-navega-aula",code:"JUEGO 01",subject:"tecnologia",title:"El agente que navega el aula",competencia:"Diseña y construye soluciones tecnológicas / Pensamiento computacional",versions:both("4.º–6.º primaria (Explorar/Resolver)","Secundaria (Diseñar, con robot programable)",[
"Programar (con bloques tipo Scratch/mBlock, o tarjetas si no hay dispositivo) la ruta de un robot o personaje para esquivar obstáculos y llegar a una meta, usando el mínimo número de bloques posible.",
["Robot educativo o app de bloques","Tablero o cuadrícula con obstáculos","Tarjetas de instrucciones (si no hay dispositivo)"],
["Armar el tablero o circuito con los obstáculos ubicados.","Colocar el robot o personaje en el punto de inicio y marcar la meta.","El equipo escribe su secuencia completa de bloques antes de ejecutar.","Ejecutan la secuencia de una sola vez, sin corregir a mitad de camino.","Cuentan el número de bloques usados y comparan con otros equipos."],
"El agente llega exactamente a la meta usando igual o menos bloques que el equipo rival.","Introducir un bucle (repetir X veces) obligatorio para poder aprobar el reto.","¿Qué parte del código tuviste que depurar y por qué fallaba?"])},
{id:"semaforo-inteligente",code:"JUEGO 02",subject:"tecnologia",title:"Semáforo inteligente",competencia:"Diseña y construye soluciones tecnológicas",versions:secondary("Secundaria (Diseñar–Optimizar)",[
"Programar un semáforo (LEDs + micro:bit/Arduino, o un simulador en línea) que cambie su temporización según una variable de entrada (sensor o botón).",["Micro:bit o Arduino + LEDs","Cables y protoboard","Alternativa: simulador online tipo Tinkercad Circuits"],["Armar el circuito con los LEDs y el microcontrolador.","Programar el ciclo básico rojo–amarillo–verde con tiempos fijos.","Agregar la variable de entrada: un botón o sensor simulado de tráfico.","Probar que el sistema cambia su comportamiento al activar la variable.","Ajustar el código si el cambio no ocurre como se esperaba."],"El sistema modifica su temporización de forma visible cuando cambia la variable de entrada.","Agregar un botón peatonal que interrumpa el ciclo normal del semáforo.","¿Qué pasaría si dos condiciones se cumplen al mismo tiempo? ¿Cómo lo resolvió tu código?"])},
{id:"hoja-calculo-detective",code:"JUEGO 03",subject:"matematica",title:"La hoja de cálculo detective",competencia:"Gestión de datos e incertidumbre",versions:both("5.º–6.º primaria (Resolver)","Secundaria (Optimizar, con fórmulas y gráficos)",[
"A partir de una base de datos simulada (asistencia, ventas de un quiosco escolar, clima de la semana), usar una hoja de cálculo para responder una pregunta concreta.",["Excel o Google Sheets","Base de datos previamente preparada por el docente"],["Repartir la base de datos ya preparada a cada equipo.","Formular con claridad la pregunta que se quiere responder.","Construir la fórmula, tabla o filtro necesario para responderla.","Elegir el tipo de gráfico adecuado según el tipo de dato.","Presentar la respuesta respaldada por el dato encontrado."],"La respuesta está respaldada por una fórmula o gráfico verificable, no solo por una opinión.","Pedir una proyección a futuro (por ejemplo, cuánto se venderá el próximo mes).","¿Qué dato te sorprendió y qué explicación posible tiene?"])},
{id:"depuradores-parejas",code:"JUEGO 04",subject:"tecnologia",title:"Depuradores en parejas",competencia:"Pensamiento computacional (depuración / debugging)",versions:both("6.º primaria (Resolver)","Secundaria (Diseñar)",[
"Un equipo recibe un algoritmo (código de bloques o pseudocódigo) con un error intencional y debe encontrarlo y corregirlo sin ejecutarlo primero, solo leyéndolo.",["Impresión del código con un error","O un proyecto Scratch compartido con la falla ya incluida"],["Entregar el código impreso o proyectado con el error oculto.","Cada integrante lo lee de forma individual, sin ejecutar nada.","En pareja, marcan la línea o bloque que creen que falla.","Explican en voz alta por qué fallaría, antes de comprobarlo.","Ejecutan el código para verificar si su hipótesis fue correcta."],"Identifican el error antes de ejecutar el código y explican correctamente por qué fallaría.","Usar un error lógico (no de sintaxis), mucho más difícil de detectar a simple vista.","¿Cómo supiste dónde buscar el error sin haber ejecutado el código?"])},
{id:"puente-estructural",code:"JUEGO 05",subject:"ingenieria",title:"El puente estructural",competencia:"Diseña y construye soluciones tecnológicas",versions:both("Desde 3.º primaria: Explorar/Resolver","Hasta 4.º secundaria: Diseñar/Optimizar",[
"Construir un puente entre dos apoyos separados que sostenga una carga creciente según el nivel: desde unir dos mesas (Explorar) hasta comparar relación resistencia/costo entre tres diseños distintos (Optimizar).",["Palitos de balsa o pajillas","Hilo y cinta adhesiva","Monedas o pesas para la prueba de carga"],["Definir la distancia entre los dos apoyos y el nivel de reto (Explorar/Resolver/Diseñar/Optimizar).","Diseñar el puente respetando los materiales y el presupuesto asignado.","Construir el puente entre los dos apoyos.","Probar el puente con la carga objetivo correspondiente al nivel.","Registrar el resultado y, si cede, rediseñar con lo aprendido en la prueba."],"El puente sostiene la carga objetivo sin ceder durante al menos 10 segundos.","En Optimizar: comparar viga, armadura y arco calculando resistencia por sol gastado.","¿Qué parte del puente cedió primero y qué principio físico lo explica?"])},
{id:"prototipo-presupuesto",code:"JUEGO 06",subject:"ingenieria",title:"Prototipo con restricción de presupuesto",competencia:"Diseña y construye soluciones tecnológicas / gestión de recursos",versions:secondary("Secundaria (Diseñar–Optimizar)",[
"Resolver un problema real del colegio (organizador de útiles, sujeta-mochilas, dispensador) con un presupuesto de materiales asignado en puntos.",["Kit variado de materiales, cada uno con un precio asignado","Lista de precios impresa"],["Presentar el problema real del colegio que se debe resolver.","Mostrar la lista de materiales disponibles con su precio en puntos.","Cada equipo planifica su compra antes de empezar a construir.","Construyen el prototipo sin exceder el presupuesto asignado.","Prueban la solución en una situación simulada lo más real posible."],"La solución funciona en la prueba simulada y no excede el presupuesto asignado.","Subastar entre equipos los materiales más escasos antes de empezar a construir.","¿Qué sacrificaste por el presupuesto y cómo afectó tu diseño final?"])},
{id:"torre-sismica",code:"JUEGO 07",subject:"ingenieria",title:"Reto de la torre sísmica",competencia:"Diseña y construye soluciones tecnológicas / explica el mundo físico",versions:both("Primaria (Resolver)","Secundaria (Optimizar, con mesa sísmica casera)",[
"Construir una torre que resista el movimiento de una base que simula un sismo (bandeja sobre pelotas o mesa que se sacude).",["Espaguetis o palitos de madera","Malvaviscos o plastilina como uniones","Bandeja móvil sobre pelotas o base con motor simple"],["Construir la base móvil que simulará el movimiento sísmico.","Cada equipo construye su torre con los materiales entregados.","Colocar la torre sobre la base y activar el movimiento.","Cronometrar cuánto tiempo resiste la torre antes de colapsar.","Analizar qué parte cedió primero y rediseñar la estructura."],"La torre permanece en pie tras 15 segundos de movimiento simulado.","Medir la intensidad del movimiento con el acelerómetro de un celular y correlacionarla con el colapso.","¿Qué característica estructural marcó la diferencia entre resistir y colapsar?"])},
{id:"redisena-envase",code:"JUEGO 08",subject:"ingenieria",title:"Rediseña el envase",competencia:"Diseña y construye soluciones tecnológicas / Arte y Cultura",versions:secondary("Secundaria (Diseñar)",[
"Rediseñar el envase de un producto escolar para reducir el material usado sin perder su función protectora.",["Cartón y papel","Balanza y regla","El envase original como referencia"],["Medir el peso y el área de material del envase original.","Identificar qué función debe conservar (proteger, contener, cerrar).","Diseñar una versión que use menos material.","Construir el nuevo envase y realizar una prueba de caída.","Comparar el peso y área del antes y el después."],"El nuevo envase usa menos material medible (peso o área) y protege el objeto en la prueba de caída.","Fijar un límite máximo de material permitido antes de empezar a diseñar.","¿Qué compromiso hiciste entre estética, costo y protección?"])},
{id:"laboratorio-variables",code:"JUEGO 09",subject:"ciencia",title:"El laboratorio de variables",competencia:"Indaga mediante métodos científicos",versions:both("Primaria (Resolver)","Secundaria (Diseñar)",[
"Diseñar un experimento simple (germinación, tiempo de disolución, rebote de una pelota) controlando una sola variable a la vez y registrando resultados.",["Materiales según el experimento elegido","Tabla de registro impresa o digital"],["Elegir el experimento y la pregunta que se quiere responder.","Definir con claridad la variable independiente, la dependiente y las que se mantendrán constantes.","Ejecutar el experimento registrando los datos en la tabla.","Repetir el experimento al menos una vez para verificar consistencia.","Concluir a partir de los datos registrados, no de la primera impresión."],"Identifican correctamente cuál es la variable independiente, la dependiente y las constantes.","Repetir el experimento cambiando dos variables a la vez y discutir por qué se confunden los resultados.","¿Qué pasaría si no hubieran controlado esa variable?"])},
{id:"encuesta-proposito",code:"JUEGO 10",subject:"matematica",title:"Encuesta con propósito",competencia:"Gestión de datos e incertidumbre / se comunica oralmente",versions:both("Primaria (Resolver)","Secundaria (Optimizar, con muestreo)",[
"Diseñar una encuesta corta sobre un problema real del colegio, aplicarla a una muestra y presentar los resultados con el gráfico adecuado.",["Formulario impreso o Google Forms","Lista de la muestra a encuestar"],["Definir el problema real del colegio que se quiere entender.","Redactar entre 3 y 5 preguntas claras y sin sesgo.","Aplicar la encuesta a la muestra definida previamente.","Tabular las respuestas y elegir el gráfico adecuado al tipo de dato.","Presentar la conclusión principal al resto del grupo."],"El gráfico elegido corresponde correctamente al tipo de dato (categórico o numérico).","En secundaria: calcular si el tamaño de la muestra es representativo del total.","¿El tamaño de tu muestra fue suficiente para sacar esa conclusión?"])},
{id:"csi-aula",code:"JUEGO 11",subject:"ciencia",title:"CSI del aula: evidencia y argumento",competencia:"Indaga mediante métodos científicos",versions:secondary("Secundaria (Diseñar)",[
"A partir de pistas preparadas (huellas, residuos, horarios), los equipos deben argumentar una hipótesis con evidencia, descartando explicaciones alternativas.",["Kit de pistas simuladas preparado por el docente","Ficha de registro de evidencia"],["Presentar la escena con las pistas ya preparadas.","Cada equipo recolecta y registra la evidencia disponible.","Proponen una hipótesis inicial sobre lo ocurrido.","Buscan evidencia que podría descartar hipótesis alternativas.","Presentan su conclusión final argumentada con evidencia concreta."],"El argumento final descarta al menos una hipótesis alternativa citando evidencia, no solo la afirma.","Incluir una pista falsa o irrelevante para poner a prueba el filtro crítico del equipo.","¿Qué evidencia habría cambiado tu conclusión?"])},
{id:"modela-ecosistema",code:"JUEGO 12",subject:"ciencia",title:"Modela el ecosistema",competencia:"Explica el mundo físico basándose en conocimientos científicos",versions:both("Primaria (Resolver)","Secundaria (Diseñar)",[
"Construir un ecosistema cerrado en un frasco (terrario) y predecir qué pasará con cada elemento si se retira uno.",["Frasco de vidrio","Tierra y plantas pequeñas","Agua"],["Armar el terrario con los elementos base (tierra, plantas, agua).","Registrar el estado inicial con un dibujo o una foto.","Predecir qué pasaría si se retira un elemento del sistema.","Observar el terrario durante varios días, registrando cambios.","Comparar la predicción inicial con lo realmente observado."],"La predicción incluye una relación causa-efecto correcta entre al menos dos elementos del sistema.","Retirar realmente un elemento (por ejemplo, la luz) y comprobar la predicción con el sistema real.","¿Qué elemento retirarías para poner a prueba tu predicción?"])},
{id:"escala-plano",code:"JUEGO 13",subject:"matematica",title:"La escala del plano",competencia:"Resuelve problemas de forma, movimiento y localización",versions:both("Primaria (Resolver)","Secundaria (Diseñar)",[
"Medir un espacio real del colegio y representarlo a escala en un plano, luego usar el plano para calcular cuánto material se necesitaría.",["Cinta métrica","Papel cuadriculado","Calculadora"],["Elegir el espacio real del colegio que se va a medir.","Medir el espacio con la cinta métrica y registrar las dimensiones.","Elegir una escala adecuada y dibujar el plano.","Usar el plano para calcular el material necesario (baldosas, pintura).","Verificar el cálculo contra una medición o cotización real."],"El plano mantiene la proporción correcta y el cálculo de material coincide con la verificación real.","Comparar el cálculo con dos escalas distintas y discutir cuál conviene más para el propósito.","¿Qué error de medición tuvo más impacto en tu cálculo final?"])},
{id:"presupuesto-imposible",code:"JUEGO 14",subject:"matematica",title:"El presupuesto imposible",competencia:"Resuelve problemas de cantidad",versions:both("Primaria (Resolver)","Secundaria (Optimizar)",[
"Planificar la compra de materiales para un proyecto de aula con un presupuesto fijo, maximizando lo que se puede construir.",["Lista de precios simulada","Ficha de planificación de compra"],["Presentar el proyecto y la lista de precios de los materiales.","Cada equipo planifica su lista de compra respetando el presupuesto.","Verifican que la suma total no excede el presupuesto asignado.","Justifican por qué esa combinación es la mejor opción posible.","Comparan su elección con la de otros equipos y discuten alternativas."],"No exceden el presupuesto y justifican con cálculos por qué esa combinación es la mejor.","Agregar un descuento por volumen que cambie la estrategia óptima de compra.","¿Qué habrías comprado distinto con un 10% más de presupuesto?"])},
{id:"patrones-predicen",code:"JUEGO 15",subject:"matematica",title:"Patrones que predicen",competencia:"Resuelve problemas de regularidad, equivalencia y cambio",versions:secondary("Secundaria (Diseñar)",[
"A partir de una secuencia de datos reales (crecimiento de una planta, ahorro semanal), encontrar el patrón y predecir un valor futuro, luego comprobarlo.",["Datos de registro previo (propio o entregado por el docente)","Calculadora"],["Presentar la secuencia de datos reales ya registrada.","Identificar el patrón o la regla que genera la secuencia.","Usar la regla para predecir un valor futuro concreto.","Comprobar la predicción contra el dato real, si ya existe, o esperar el resultado.","Discutir el margen de error entre la predicción y el dato real."],"La predicción se acerca al valor real dentro de un margen razonable, justificado con la regla encontrada.","Pedir que prueben si su regla sigue funcionando muy lejos en el futuro (extrapolación extrema).","¿Tu regla seguiría funcionando muy lejos en el futuro? ¿Por qué sí o no?"])},
{id:"infografia-datos",code:"JUEGO 16",subject:"arte",title:"Infografía con datos propios",competencia:"Crea proyectos desde los lenguajes artísticos / gestión de datos",versions:both("Primaria (Resolver)","Secundaria (Diseñar)",[
"Convertir los datos de otro juego del banco (encuesta, experimento) en una infografía visualmente clara para un público específico.",["Cartulina y marcadores, o Canva/PowerPoint","Los datos ya trabajados en otro juego"],["Elegir los datos de otro juego del banco ya trabajado previamente.","Definir el mensaje principal y el público objetivo de la infografía.","Bocetar la jerarquía visual antes de pasar a la versión final.","Construir la infografía en cartulina o en una herramienta digital.","Probarla con un lector externo y ajustar lo que no se entienda."],"Un lector externo entiende el mensaje principal en menos de 30 segundos.","Limitar la infografía a un solo color y una sola imagen, obligando a priorizar la información.","¿Qué elemento visual eliminarías para que el mensaje fuera más claro?"])},
{id:"reto-final-steam",code:"JUEGO 17",subject:"ingenieria",title:"El reto final STEAM: proyecto integrador",competencia:"Integra varias competencias — cierre de unidad",versions:both("Primaria alta (Diseñar)","Secundaria (Optimizar)",[
"En equipos, identificar un problema real del colegio o comunidad y proponer una solución que combine datos, un prototipo o sistema, y una presentación.",["Materiales libres, según el proyecto elegido por cada equipo"],["Identificar en equipo un problema real del colegio o la comunidad.","Recolectar evidencia (datos, fotos, testimonios) que demuestre que el problema existe.","Diseñar y construir una solución o prototipo para el problema.","Preparar la presentación integrando datos, prototipo y argumento.","Presentar ante el grupo y responder preguntas del público."],"El equipo presenta evidencia del problema, un prototipo funcional o simulado, y responde preguntas del público.","Invitar a un público externo (otro grado, padres de familia) para elevar la exigencia de la presentación.","¿Qué parte de tu proyecto no pudiste probar y cómo lo argumentarías igual?"])},
];

const DETAILS={
"agente-navega-aula":{tiempo:"45 a 60 minutos",organizacion:"Equipos de 3 o 4: programador, verificador de ruta y relator.",preparacion:["Dibuja una cuadrícula amplia y coloca entre 3 y 5 obstáculos visibles.","Prepara tarjetas de avanzar, girar a la derecha, girar a la izquierda y repetir.","Prueba previamente una ruta válida y define el máximo de bloques permitido."],acompanamiento:["¿En qué casilla debería terminar después de esta instrucción?","¿Qué instrucciones se repiten y podrían convertirse en un bucle?","Antes de ejecutar, recorran el algoritmo con el dedo y localicen un posible error."],evidencias:["Secuencia de instrucciones escrita antes de ejecutar.","Registro del primer intento y de la corrección realizada.","Explicación del equipo sobre cómo redujo el número de bloques."]},
"semaforo-inteligente":{tiempo:"90 minutos o dos sesiones",organizacion:"Equipos de 3: responsable del circuito, programador y encargado de pruebas.",preparacion:["Comprueba que cada kit encienda sus tres LEDs o deja listo el simulador.","Entrega el diagrama del circuito y una tabla para registrar tiempos y respuestas.","Plantea un caso real: congestión vehicular o cruce peatonal cercano al colegio."],acompanamiento:["¿Qué entrada detectará el sistema y qué salida debe modificar?","¿Cómo comprobarán que el cambio no ocurrió por casualidad?","¿Qué condición debe tener prioridad si se presionan dos botones?"],evidencias:["Diagrama del circuito y algoritmo.","Video o demostración de la respuesta ante la variable.","Tabla de pruebas con error detectado y ajuste realizado."]},
"hoja-calculo-detective":{tiempo:"45 a 60 minutos",organizacion:"Parejas con una copia de la base de datos y una pregunta de investigación.",preparacion:["Revisa que la base contenga encabezados claros y datos suficientes.","Prepara una pregunta distinta por pareja o equipo.","Incluye un dato atípico para promover la interpretación crítica."],acompanamiento:["¿Qué columnas necesitan realmente para responder?","¿La fórmula calcula lo que pregunta el problema?","¿Por qué ese gráfico comunica mejor el hallazgo que otro?"],evidencias:["Hoja de cálculo con fórmula, filtro o tabla dinámica.","Gráfico con título, variables y etiquetas legibles.","Conclusión escrita que cita al menos un dato exacto."]},
"depuradores-parejas":{tiempo:"35 a 45 minutos",organizacion:"Parejas: detective de código y argumentador; luego intercambian roles.",preparacion:["Prepara un algoritmo breve con un único error intencional.","Imprime una versión por pareja y conserva una versión correcta.","Define la salida esperada para que puedan contrastar su hipótesis."],acompanamiento:["¿Qué debería ocurrir en cada bloque?","¿En qué momento la salida deja de coincidir con lo esperado?","¿El error está en el orden, la condición o la repetición?"],evidencias:["Código marcado antes de ejecutarlo.","Hipótesis escrita sobre la causa del error.","Versión corregida y explicación de la verificación."]},
"puente-estructural":{tiempo:"90 minutos o dos sesiones",organizacion:"Equipos de 4: diseñador, responsable de materiales, constructor y registrador.",preparacion:["Coloca dos apoyos a la misma distancia para todos los equipos.","Entrega exactamente la misma cantidad de materiales.","Prepara una zona segura para agregar monedas de una en una."],acompanamiento:["¿Dónde se concentra la carga?","¿Qué forma puede distribuir mejor el peso?","¿Qué cambiarán después de observar el primer punto de falla?"],evidencias:["Boceto inicial con medidas.","Tabla de carga soportada en cada intento.","Comparación entre diseño inicial y rediseño con justificación."]},
"prototipo-presupuesto":{tiempo:"90 a 120 minutos",organizacion:"Equipos de 4 con presupuesto común y roles rotativos.",preparacion:["Selecciona un problema real y observable del colegio.","Etiqueta cada material con un costo en puntos.","Prepara una ficha de compras, presupuesto y prueba funcional."],acompanamiento:["¿Qué necesidad indispensable debe resolver el prototipo?","¿Qué material aporta más valor por su costo?","¿Qué prueba reproducirá mejor la situación real?"],evidencias:["Plan de compra con suma total.","Boceto del prototipo y criterio de funcionamiento.","Resultado de la prueba y decisión de mejora."]},
"torre-sismica":{tiempo:"60 a 90 minutos",organizacion:"Equipos de 4: arquitecto, constructor, encargado de prueba y registrador.",preparacion:["Construye y prueba una base móvil con intensidad semejante para todos.","Define altura mínima y cantidad exacta de materiales.","Marca una zona de seguridad y prepara un cronómetro."],acompanamiento:["¿Cómo influye el ancho de la base?","¿Dónde conviene colocar refuerzos diagonales?","¿Qué parte se movió primero y qué ajuste harán?"],evidencias:["Boceto estructural.","Tiempo de resistencia y observación del punto de colapso.","Rediseño que incorpora lo aprendido en la prueba."]},
"redisena-envase":{tiempo:"90 minutos",organizacion:"Parejas o equipos de 3 con un envase y un objeto de prueba.",preparacion:["Reúne envases limpios de tamaño semejante.","Define altura de caída y condición de protección.","Entrega una ficha para registrar peso, área y resultado."],acompanamiento:["¿Qué parte cumple una función y cuál solo añade material?","¿Cómo disminuirán material sin debilitar el cierre?","¿Qué evidencia demostrará que el objeto quedó protegido?"],evidencias:["Mediciones antes y después.","Plantilla o desarrollo del nuevo envase.","Resultado documentado de la prueba de caída."]},
"laboratorio-variables":{tiempo:"60 minutos más observaciones posteriores",organizacion:"Equipos de 4 con roles de investigador, encargado de materiales, medidor y registrador.",preparacion:["Elige un experimento seguro y realizable con los recursos del aula.","Prepara una tabla con variable independiente, dependiente y constantes.","Asegura al menos dos repeticiones por condición."],acompanamiento:["¿Qué cambiarán intencionalmente?","¿Qué medirán para observar el efecto?","¿Qué debe permanecer igual para comparar de manera justa?"],evidencias:["Pregunta e hipótesis.","Tabla de variables y resultados de las repeticiones.","Conclusión que contrasta la hipótesis con los datos."]},
"encuesta-proposito":{tiempo:"Dos sesiones de 45 minutos",organizacion:"Equipos de 4: redactor, encuestador, tabulador y portavoz.",preparacion:["Selecciona problemas que los estudiantes puedan investigar éticamente.","Revisa ejemplos de preguntas neutrales y preguntas sesgadas.","Define población y muestra antes de aplicar el formulario."],acompanamiento:["¿La pregunta orienta al encuestado hacia una respuesta?","¿A quiénes deben consultar para representar al grupo?","¿Qué gráfico corresponde al tipo de respuesta?"],evidencias:["Formulario revisado.","Base de respuestas y gráfico.","Conclusión que reconoce el alcance y límites de la muestra."]},
"csi-aula":{tiempo:"60 a 90 minutos",organizacion:"Equipos de 4: recolector, registrador, analista y argumentador.",preparacion:["Construye un caso ficticio sin acusar a personas reales.","Prepara pistas relevantes, una pista irrelevante y una cronología.","Entrega una ficha para distinguir observación de interpretación."],acompanamiento:["¿Qué observan exactamente y qué están suponiendo?","¿Qué hipótesis alternativa explica también esa pista?","¿Qué evidencia permite descartar una explicación?"],evidencias:["Inventario de evidencias.","Matriz de hipótesis y pistas que las apoyan o contradicen.","Argumento final con afirmación, evidencia y razonamiento."]},
"modela-ecosistema":{tiempo:"45 minutos de montaje y seguimiento de 7 a 10 días",organizacion:"Equipos de 3 con un terrario y un calendario de observación.",preparacion:["Selecciona plantas pequeñas y recipientes transparentes seguros.","Define cantidad de tierra y agua para evitar diferencias innecesarias.","Prepara una ficha de observación diaria con dibujo o fotografía."],acompanamiento:["¿Qué función cumple cada componente?","¿Qué cambio esperan observar primero y por qué?","¿Qué evidencia confirma o contradice su predicción?"],evidencias:["Modelo inicial etiquetado.","Predicción causa-efecto.","Registro cronológico y comparación final."]},
"escala-plano":{tiempo:"90 minutos",organizacion:"Equipos de 3: medidor, dibujante y verificador de cálculos.",preparacion:["Selecciona un espacio accesible y delimita las zonas de medición.","Repasa equivalencias y presenta un ejemplo sencillo de escala.","Entrega papel cuadriculado, tabla de medidas y lista de precios opcional."],acompanamiento:["¿Qué escala permitirá que todo el espacio entre en la hoja?","¿Cómo comprobarán que las proporciones se mantienen?","¿Qué medida influye más en el cálculo de material?"],evidencias:["Croquis con medidas reales.","Plano a escala con leyenda.","Cálculo de material y verificación."]},
"presupuesto-imposible":{tiempo:"45 a 60 minutos",organizacion:"Equipos de 3 con el mismo presupuesto y lista de precios.",preparacion:["Diseña una lista con opciones, cantidades y precios realistas.","Define qué necesita mínimamente el proyecto.","Incluye restricciones que obliguen a priorizar."],acompanamiento:["¿Qué compra es indispensable y cuál puede reemplazarse?","¿Cómo demostrarán que su combinación es conveniente?","¿Qué pasaría si cambia el precio de un producto?"],evidencias:["Lista de compra con operaciones.","Saldo final y comprobación del límite.","Justificación comparativa de la decisión."]},
"patrones-predicen":{tiempo:"45 a 60 minutos",organizacion:"Parejas que analizan una serie y contrastan reglas posibles.",preparacion:["Selecciona datos reales con suficientes términos y patrón identificable.","Oculta uno o dos valores para utilizarlos como verificación.","Prepara una tabla y, si corresponde, un plano cartesiano."],acompanamiento:["¿La diferencia o razón se mantiene?","¿Cómo escribirían la regla con palabras o símbolos?","¿En qué condiciones dejaría de funcionar su predicción?"],evidencias:["Tabla con regularidades marcadas.","Regla verbal, gráfica o algebraica.","Predicción, comprobación y cálculo del error."]},
"infografia-datos":{tiempo:"90 minutos",organizacion:"Parejas: responsable de datos y responsable del diseño; ambos revisan el mensaje.",preparacion:["Selecciona previamente datos válidos de una encuesta o experimento.","Muestra ejemplos de jerarquía visual sin entregar una plantilla cerrada.","Define público, formato y prueba con lector externo."],acompanamiento:["¿Cuál es el único mensaje que debe recordar el público?","¿Qué dato merece mayor tamaño o contraste?","¿Hay elementos decorativos que dificultan la comprensión?"],evidencias:["Boceto con jerarquía.","Infografía final con fuente de datos.","Retroalimentación del lector y ajuste realizado."]},
"reto-final-steam":{tiempo:"Proyecto de 3 a 5 sesiones",organizacion:"Equipos de 4 o 5 con roles acordados y bitácora compartida.",preparacion:["Delimita problemas alcanzables del colegio o comunidad.","Define hitos: investigación, diseño, prototipo, prueba y presentación.","Entrega criterios para valorar evidencia, funcionamiento y argumentación."],acompanamiento:["¿Qué evidencia demuestra que el problema existe?","¿Para quién diseñan y qué necesidad concreta atenderán?","¿Qué parte probarán, cómo recogerán resultados y qué mejorarán?"],evidencias:["Definición del problema sustentada con datos o testimonios.","Bocetos, bitácora y pruebas del prototipo.","Presentación final con argumento y respuesta a preguntas."]}
};

export const GUIDE_ACTIVITIES=GUIDE_BASE.map(activity=>({...activity,detalle:DETAILS[activity.id]}));
