// scripts/atlas-lexico.es.mjs
//
// LÉXICO ANATÓMICO INGLÉS → ESPAÑOL
//
// POR QUÉ ESTO Y NO UN TRADUCTOR
// ------------------------------
// Los 2.234 nombres de BodyParts3D vienen en inglés y hay que enseñarlos en
// español a docentes peruanos. Traducirlos en el navegador estaba descartado
// por el encargo, y con razón: una traducción automática convierte «Left
// lower first secondary molar tooth» en algo que ningún odontólogo reconoce.
//
// Los nombres no son prosa: son composiciones regladas. 614 términos
// distintos cubren los 2.234 nombres. Así que se traduce el término una vez,
// a mano, y un generador compone el resto siguiendo el orden del español.
// El resultado se escribe en `public/models/atlas-es.json` y se versiona: lo
// que ve la docente está revisado, no adivinado en caliente.
//
// CÓMO SE COMPONE
// ---------------
// El inglés antepone los modificadores al núcleo y el español los pospone:
//
//   Right common carotid artery  →  Arteria carótida común derecha
//   [lado] [mod] [mod] [NÚCLEO]  →  [NÚCLEO] [mod] [mod] [lado]
//
// De ahí que cada núcleo lleve género: «arteria» pide «carótida común
// derecha» y «nervio» pide «óptico derecho». Sin género, la mitad de los
// nombres saldrían mal concordados.

/* ==========================================================================
   NÚCLEOS · el sustantivo que manda en el nombre
   `g` es el género para concordar los modificadores: "m" o "f".
   ========================================================================== */
export const NUCLEOS = {
  // --- vasos y circulación
  artery: { es: "Arteria", g: "f" },
  arteries: { es: "Arterias", g: "f", pl: true },
  arteria: { es: "Arteria", g: "f" },
  vein: { es: "Vena", g: "f" },
  veins: { es: "Venas", g: "f", pl: true },
  aorta: { es: "Aorta", g: "f" },
  vena: { es: "Vena", g: "f" },
  trunk: { es: "Tronco", g: "m" },
  choroid: { es: "Coroides", g: "f" },
  branch: { es: "Rama", g: "f" },
  branches: { es: "Ramas", g: "f", pl: true },
  tributary: { es: "Afluente", g: "m" },
  network: { es: "Red", g: "f" },
  arch: { es: "Arco", g: "m" },
  valve: { es: "Válvula", g: "f" },
  cusp: { es: "Cúspide", g: "f" },
  leaflet: { es: "Valva", g: "f" },
  atrium: { es: "Aurícula", g: "f" },
  ventricle: { es: "Ventrículo", g: "m" },

  // --- nervios y sistema nervioso
  nerve: { es: "Nervio", g: "m" },
  plexus: { es: "Plexo", g: "m" },
  ganglion: { es: "Ganglio", g: "m" },
  nucleus: { es: "Núcleo", g: "m" },
  gyrus: { es: "Circunvolución", g: "f" },
  sulcus: { es: "Surco", g: "m" },
  cortex: { es: "Corteza", g: "f" },
  tract: { es: "Tracto", g: "m" },
  commissure: { es: "Comisura", g: "f" },
  peduncle: { es: "Pedúnculo", g: "m" },
  colliculus: { es: "Colículo", g: "m" },
  stria: { es: "Estría", g: "f" },
  hemisphere: { es: "Hemisferio", g: "m" },
  lobule: { es: "Lobulillo", g: "m" },
  capsule: { es: "Cápsula", g: "f" },
  aqueduct: { es: "Acueducto", g: "m" },
  habenula: { es: "Habénula", g: "f" },
  chiasm: { es: "Quiasma", g: "m" },
  fornix: { es: "Fórnix", g: "m" },
  insula: { es: "Ínsula", g: "f" },
  amygdala: { es: "Amígdala", g: "f" },
  hippocampus: { es: "Hipocampo", g: "m" },
  thalamus: { es: "Tálamo", g: "m" },
  hypothalamus: { es: "Hipotálamo", g: "m" },
  putamen: { es: "Putamen", g: "m" },
  pallidus: { es: "Globo pálido", g: "m" },
  cerebellum: { es: "Cerebelo", g: "m" },
  midbrain: { es: "Mesencéfalo", g: "m" },
  forebrain: { es: "Prosencéfalo", g: "m" },
  telencephalon: { es: "Telencéfalo", g: "m" },
  pons: { es: "Puente", g: "m" },
  medulla: { es: "Bulbo", g: "m" },
  brachium: { es: "Brazo", g: "m" },
  tentorium: { es: "Tienda", g: "f" },
  tuber: { es: "Tuber", g: "m" },

  // --- músculos, huesos y tejidos
  muscle: { es: "Músculo", g: "m" },
  tendon: { es: "Tendón", g: "m" },
  ligament: { es: "Ligamento", g: "m" },
  bone: { es: "Hueso", g: "m" },
  cartilage: { es: "Cartílago", g: "m" },
  membrane: { es: "Membrana", g: "f" },
  retinaculum: { es: "Retináculo", g: "m" },
  aponeurosis: { es: "Aponeurosis", g: "f" },
  raphe: { es: "Rafe", g: "m" },
  taenia: { es: "Tenia", g: "f" },
  sphincter: { es: "Esfínter", g: "m" },
  vertebra: { es: "Vértebra", g: "f" },
  rib: { es: "Costilla", g: "f" },
  phalanx: { es: "Falange", g: "f" },
  disk: { es: "Disco", g: "m" },
  sesamoid: { es: "Sesamoideo", g: "m" },
  process: { es: "Apófisis", g: "f" },
  lamina: { es: "Lámina", g: "f" },
  plate: { es: "Lámina", g: "f" },
  septum: { es: "Tabique", g: "m" },
  fossa: { es: "Fosa", g: "f" },
  foramen: { es: "Agujero", g: "m" },
  concha: { es: "Cornete", g: "m" },

  // --- vísceras, glándulas y conductos
  gland: { es: "Glándula", g: "f" },
  lobe: { es: "Lóbulo", g: "m" },
  duct: { es: "Conducto", g: "m" },
  canal: { es: "Conducto", g: "m" },
  canaliculus: { es: "Canalículo", g: "m" },
  sinus: { es: "Seno", g: "m" },
  sac: { es: "Saco", g: "m" },
  lake: { es: "Lago", g: "m" },
  cavity: { es: "Cavidad", g: "f" },
  chamber: { es: "Cámara", g: "f" },
  bronchus: { es: "Bronquio", g: "m" },
  parenchyma: { es: "Parénquima", g: "m" },
  mesentery: { es: "Mesenterio", g: "m" },
  mesocolon: { es: "Mesocolon", g: "m" },
  mesoappendix: { es: "Mesoapéndice", g: "m" },

  // --- estructuras generales
  part: { es: "Porción", g: "f" },
  segment: { es: "Segmento", g: "m" },
  set: { es: "Conjunto", g: "m" },
  tree: { es: "Árbol", g: "m" },
  division: { es: "División", g: "f" },
  junction: { es: "Unión", g: "f" },
  wall: { es: "Pared", g: "f" },
  body: { es: "Cuerpo", g: "m" },
  head: { es: "Cabeza", g: "f" },
  cord: { es: "Cordón", g: "m" },
  limb: { es: "Brazo", g: "m" },
  matter: { es: "Sustancia", g: "f" },
  corpus: { es: "Cuerpo", g: "m" },
  globus: { es: "Globo", g: "m" },
  eyeball: { es: "Globo ocular", g: "m" },
  eyelid: { es: "Párpado", g: "m" },
  lens: { es: "Cristalino", g: "m" },
  iris: { es: "Iris", g: "m" },
  cornea: { es: "Córnea", g: "f" },
  retina: { es: "Retina", g: "f" },
  sclera: { es: "Esclerótica", g: "f" },
  corona: { es: "Corona", g: "f" },
  trochlea: { es: "Tróclea", g: "f" },
  gingiva: { es: "Encía", g: "f" },
  jaw: { es: "Maxilar", g: "m" },
  tooth: { es: "Diente", g: "m" },
  tongue: { es: "Lengua", g: "f" },
  skin: { es: "Piel", g: "f" },
  ear: { es: "Oreja", g: "f" },
  eyebrow: { es: "Ceja", g: "f" },
  lip: { es: "Labio", g: "m" },
  hair: { es: "Vello", g: "m" },
  diaphragm: { es: "Diafragma", g: "m" },
  liver: { es: "Hígado", g: "m" },
  spleen: { es: "Bazo", g: "m" },
  stomach: { es: "Estómago", g: "m" },
  pancreas: { es: "Páncreas", g: "m" },
  kidney: { es: "Riñón", g: "m" },
  bladder: { es: "Vejiga", g: "f" },
  prostate: { es: "Próstata", g: "f" },
  testis: { es: "Testículo", g: "m" },
  epididymis: { es: "Epidídimo", g: "m" },
  thymus: { es: "Timo", g: "m" },
  appendix: { es: "Apéndice", g: "m" },
  rectum: { es: "Recto", g: "m" },
  duodenum: { es: "Duodeno", g: "m" },
  jejunum: { es: "Yeyuno", g: "m" },
  ileum: { es: "Íleon", g: "m" },
  colon: { es: "Colon", g: "m" },
  esophagus: { es: "Esófago", g: "m" },
  intestine: { es: "Intestino", g: "m" },
  gallbladder: { es: "Vesícula biliar", g: "f" },
  ureter: { es: "Uréter", g: "m" },
  urethra: { es: "Uretra", g: "f" },
  trachea: { es: "Tráquea", g: "f" },
  epiglottis: { es: "Epiglotis", g: "f" },
  vesicle: { es: "Vesícula", g: "f" },
  glans: { es: "Glande", g: "m" },
  penis: { es: "Pene", g: "m" },
  thyroid: { es: "Tiroides", g: "f" },
  pituitary: { es: "Hipófisis", g: "f" },
  cerebelli: { es: "del cerebelo", g: "m" },

  // --- huesos con nombre propio
  femur: { es: "Fémur", g: "m" },
  tibia: { es: "Tibia", g: "f" },
  fibula: { es: "Peroné", g: "m" },
  humerus: { es: "Húmero", g: "m" },
  radius: { es: "Radio", g: "m" },
  ulna: { es: "Cúbito", g: "m" },
  scapula: { es: "Escápula", g: "f" },
  clavicle: { es: "Clavícula", g: "f" },
  sternum: { es: "Esternón", g: "m" },
  manubrium: { es: "Manubrio", g: "m" },
  patella: { es: "Rótula", g: "f" },
  talus: { es: "Astrágalo", g: "m" },
  calcaneus: { es: "Calcáneo", g: "m" },
  cuboid: { es: "Cuboides", g: "m" },
  navicular: { es: "Navicular", g: "m" },
  lunate: { es: "Semilunar", g: "m" },
  capitate: { es: "Hueso grande", g: "m" },
  hamate: { es: "Ganchoso", g: "m" },
  pisiform: { es: "Pisiforme", g: "m" },
  scaphoid: { es: "Escafoides", g: "m" },
  trapezium: { es: "Trapecio", g: "m" },
  trapezoid: { es: "Trapezoide", g: "m" },
  triquetral: { es: "Piramidal", g: "m" },
  maxilla: { es: "Maxilar", g: "m" },
  mandible: { es: "Mandíbula", g: "f" },
  vomer: { es: "Vómer", g: "m" },
  ethmoid: { es: "Etmoides", g: "m" },
  sphenoid: { es: "Esfenoides", g: "m" },
  sacrum: { es: "Sacro", g: "m" },
  atlas: { es: "Atlas", g: "m" },
  axis: { es: "Axis", g: "m" },
  hyoid: { es: "Hioides", g: "m" },
  cricoid: { es: "Cricoides", g: "m" },
  arytenoid: { es: "Aritenoides", g: "m" },
  hip: { es: "Coxal", g: "m" },
  metacarpal: { es: "Metacarpiano", g: "m" },
  metatarsal: { es: "Metatarsiano", g: "m" },
  carpal: { es: "Carpiano", g: "m" },
  tarsal: { es: "Tarsiano", g: "m" },

  // --- regiones del cuerpo (aparecen como núcleo tras "of")
  hand: { es: "Mano", g: "f" },
  foot: { es: "Pie", g: "m" },
  finger: { es: "Dedo de la mano", g: "m" },
  toe: { es: "Dedo del pie", g: "m" },
  thumb: { es: "Pulgar", g: "m" },
  wrist: { es: "Muñeca", g: "f" },
  forearm: { es: "Antebrazo", g: "m" },
  leg: { es: "Pierna", g: "f" },
};

/* ==========================================================================
   MODIFICADORES · adjetivos y calificativos.
   Cuando el masculino y el femenino difieren, se dan los dos.
   ========================================================================== */
export const MODIFICADORES = {
  // posición y orientación
  right: { m: "derecho", f: "derecha" },
  left: { m: "izquierdo", f: "izquierda" },
  superior: "superior",
  inferior: "inferior",
  anterior: "anterior",
  posterior: "posterior",
  lateral: "lateral",
  medial: "medial",
  middle: { m: "medio", f: "media" },
  intermediate: { m: "intermedio", f: "intermedia" },
  intermedius: { m: "intermedio", f: "intermedia" },
  internal: { m: "interno", f: "interna" },
  internus: { m: "interno", f: "interna" },
  external: { m: "externo", f: "externa" },
  externus: { m: "externo", f: "externa" },
  deep: { m: "profundo", f: "profunda" },
  profundus: { m: "profundo", f: "profunda" },
  superficial: "superficial",
  superficialis: "superficial",
  central: "central",
  peripheral: "periférico",
  proximal: "proximal",
  distal: "distal",
  upper: "superior",
  lower: "inferior",
  dorsal: "dorsal",
  dorsalis: "dorsal",
  ventral: "ventral",
  palmar: "palmar",
  plantar: "plantar",
  basal: "basal",
  apical: "apical",
  caudal: "caudal",
  cranial: "craneal",
  transverse: { m: "transverso", f: "transversa" },
  transversus: { m: "transverso", f: "transversa" },
  oblique: { m: "oblicuo", f: "oblicua" },
  obliquus: { m: "oblicuo", f: "oblicua" },
  vertical: "vertical",
  straight: { m: "recto", f: "recta" },
  ascending: "ascendente",
  descending: "descendente",
  recurrent: "recurrente",
  circumflex: { m: "circunflejo", f: "circunfleja" },
  arcuate: { m: "arqueado", f: "arqueada" },
  perforating: "perforante",
  communicating: "comunicante",
  collateral: "colateral",
  marginal: "marginal",
  terminal: "terminal",
  terminalis: "terminal",
  accessory: { m: "accesorio", f: "accesoria" },
  accessorius: { m: "accesorio", f: "accesoria" },
  common: { m: "común", f: "común" },
  proper: { m: "propio", f: "propia" },
  main: { m: "principal", f: "principal" },
  primary: { m: "primario", f: "primaria" },
  secondary: { m: "permanente", f: "permanente" },
  anterolateral: "anterolateral",
  posteromedial: "posteromedial",
  mediobasal: "mediobasal",
  laterobasal: "laterobasal",
  subsuperior: "subsuperior",
  innermost: { m: "íntimo", f: "íntima" },
  precommunicating: "precomunicante",
  postcommunicating: "poscomunicante",
  polar: "polar",
  medullaris: "medular",

  // tamaño y forma
  great: { m: "mayor", f: "mayor" },
  greater: { m: "mayor", f: "mayor" },
  major: { m: "mayor", f: "mayor" },
  magnus: { m: "mayor", f: "mayor" },
  maximus: { m: "mayor", f: "mayor" },
  minor: { m: "menor", f: "menor" },
  minimus: { m: "menor", f: "menor" },
  minimi: { m: "menor", f: "menor" },
  small: { m: "pequeño", f: "pequeña" },
  big: { m: "grueso", f: "gruesa" },
  little: { m: "meñique", f: "meñique" },
  long: { m: "largo", f: "larga" },
  longus: { m: "largo", f: "larga" },
  longi: { m: "largos", f: "largas" },
  longissimus: { m: "largo", f: "larga" },
  short: { m: "corto", f: "corta" },
  brevis: { m: "corto", f: "corta" },
  breves: { m: "cortos", f: "cortas" },
  white: { m: "blanca", f: "blanca" },

  // orden
  first: { m: "primer", f: "primera" },
  second: { m: "segundo", f: "segunda" },
  third: { m: "tercer", f: "tercera" },
  fourth: { m: "cuarto", f: "cuarta" },
  fifth: { m: "quinto", f: "quinta" },
  sixth: { m: "sexto", f: "sexta" },
  seventh: { m: "séptimo", f: "séptima" },
  eighth: { m: "octavo", f: "octava" },
  ninth: { m: "noveno", f: "novena" },
  tenth: { m: "décimo", f: "décima" },
  eleventh: { m: "undécimo", f: "undécima" },
  twelfth: { m: "duodécimo", f: "duodécima" },
  tertius: { m: "tercero", f: "tercera" },
  index: { m: "índice", f: "índice" },
  indicis: { m: "del índice", f: "del índice" },
  ring: { m: "anular", f: "anular" },

  // regionales
  cervical: "cervical",
  cervicis: "del cuello",
  colli: "del cuello",
  capitis: "de la cabeza",
  thoracic: { m: "torácico", f: "torácica" },
  thoracis: { m: "torácico", f: "torácica" },
  lumbar: "lumbar",
  lumborum: "lumbar",
  sacral: { m: "sacro", f: "sacra" },
  coccygeus: { m: "coccígeo", f: "coccígea" },
  abdominal: "abdominal",
  pelvic: { m: "pélvico", f: "pélvica" },
  perineal: "perineal",
  pubic: { m: "púbico", f: "púbica" },
  anal: "anal",
  costal: "costal",
  costarum: "costales",
  intercostal: "intercostal",
  subcostal: "subcostal",
  sternocostal: "esternocostal",
  clavicular: "clavicular",
  acromial: "acromial",
  scapular: "escapular",
  scapulae: "de la escápula",
  axillary: "axilar",
  brachial: "braquial",
  brachii: "del brazo",
  antebrachial: "antebraquial",
  cubital: "cubital",
  radial: "radial",
  radialis: "radial",
  ulnar: "cubital",
  ulnaris: "cubital",
  carpi: "del carpo",
  digital: "digital",
  digiti: "del dedo",
  digitorum: "de los dedos",
  pollicis: "del pulgar",
  hallucis: "del dedo gordo",
  interosseous: { m: "interóseo", f: "interósea" },
  interossei: { m: "interóseos", f: "interóseas" },
  femoral: "femoral",
  femoris: "femoral",
  genicular: "de la rodilla",
  popliteal: { m: "poplíteo", f: "poplítea" },
  tibial: "tibial",
  fibular: "peroneo",
  fibularis: "peroneo",
  calcaneal: { m: "calcáneo", f: "calcánea" },
  saphenous: { m: "safeno", f: "safena" },
  iliac: { m: "ilíaco", f: "ilíaca" },
  iliolumbar: "iliolumbar",
  inguinal: "inguinal",
  gluteal: { m: "glúteo", f: "glútea" },
  obturator: { m: "obturador", f: "obturatriz" },
  pudendal: { m: "pudendo", f: "pudenda" },
  testicular: "testicular",
  renal: "renal",
  suprarenal: "suprarrenal",
  adrenal: "suprarrenal",
  ureteric: "ureteral",
  urinary: { m: "urinario", f: "urinaria" },
  hepatic: { m: "hepático", f: "hepática" },
  hepatovenous: { m: "hepatovenoso", f: "hepatovenosa" },
  "pre-hepatic": { m: "prehepático", f: "prehepática" },
  biliary: "biliar",
  cystic: { m: "cístico", f: "cística" },
  portal: "porta",
  splenic: { m: "esplénico", f: "esplénica" },
  gastric: { m: "gástrico", f: "gástrica" },
  gastroduodenal: "gastroduodenal",
  "gastro-epiploic": { m: "gastroepiploico", f: "gastroepiploica" },
  gastroepiploic: { m: "gastroepiploico", f: "gastroepiploica" },
  pancreatic: { m: "pancreático", f: "pancreática" },
  pancreaticoduodenal: "pancreaticoduodenal",
  mesenteric: { m: "mesentérico", f: "mesentérica" },
  colic: { m: "cólico", f: "cólica" },
  ileocolic: { m: "ileocólico", f: "ileocólica" },
  ileal: "ileal",
  ileocecal: "ileocecal",
  cecal: { m: "cecal", f: "cecal" },
  appendicular: "apendicular",
  sigmoid: { m: "sigmoideo", f: "sigmoidea" },
  rectal: "rectal",
  esophageal: { m: "esofágico", f: "esofágica" },
  oesophageal: { m: "esofágico", f: "esofágica" },
  epigastric: { m: "epigástrico", f: "epigástrica" },
  phrenic: { m: "frénico", f: "frénica" },
  musculophrenic: { m: "musculofrénico", f: "musculofrénica" },
  celiac: { m: "celíaco", f: "celíaca" },
  omentalis: "omental",
  mesocolica: "mesocólica",
  libera: "libre",

  // tórax, corazón y pulmón
  cardiac: { m: "cardíaco", f: "cardíaca" },
  coronary: { m: "coronario", f: "coronaria" },
  interventricular: "interventricular",
  ventricular: "ventricular",
  septal: { m: "septal", f: "septal" },
  papillary: { m: "papilar", f: "papilar" },
  diagonal: "diagonal",
  aortic: { m: "aórtico", f: "aórtica" },
  mitral: "mitral",
  tricuspid: { m: "tricúspide", f: "tricúspide" },
  pulmonary: { m: "pulmonar", f: "pulmonar" },
  bronchial: { m: "bronquial", f: "bronquial" },
  lobar: "lobar",
  lingular: "lingular",
  segmental: { m: "segmentario", f: "segmentaria" },
  azygos: "ácigos",
  hemiazygos: "hemiácigos",
  brachiocephalic: { m: "braquiocefálico", f: "braquiocefálica" },
  subclavian: { m: "subclavio", f: "subclavia" },
  subclavius: { m: "subclavio", f: "subclavia" },
  thyrocervical: { m: "tirocervical", f: "tirocervical" },
  costocervical: { m: "costocervical", f: "costocervical" },
  thoracodorsal: "toracodorsal",
  "thoraco-acromial": { m: "toracoacromial", f: "toracoacromial" },
  subscapular: { m: "subescapular", f: "subescapular" },
  suprascapular: { m: "supraescapular", f: "supraescapular" },
  princeps: { m: "principal", f: "principal" },
  humeral: "humeral",
  pectoral: { m: "pectoral", f: "pectoral" },

  // cabeza, cuello y cara
  carotid: { m: "carotídeo", f: "carótida" },
  jugular: "yugular",
  vertebral: "vertebral",
  basilar: "basilar",
  cerebral: "cerebral",
  cerebellar: { m: "cerebeloso", f: "cerebelosa" },
  vermian: { m: "vermiano", f: "vermiana" },
  pontine: "pontina",
  choroidal: { m: "coroideo", f: "coroidea" },
  choroid: { m: "coroideo", f: "coroidea" },
  thalamogeniculate: "talamogeniculada",
  thalamoperforating: "talamoperforante",
  hypothalamic: { m: "hipotalámico", f: "hipotalámica" },
  intermediomedial: "intermediomedial",
  geniculate: { m: "geniculado", f: "geniculada" },
  interpeduncular: "interpeduncular",
  mammillary: { m: "mamilar", f: "mamilar" },
  oblongata: { m: "raquídeo", f: "raquídea" },
  cinereum: { m: "cinéreo", f: "cinérea" },
  callosum: { m: "calloso", f: "callosa" },
  callosomarginal: "callosomarginal",
  pericallosal: "pericallosa",
  splenial: { m: "esplenial", f: "esplenial" },
  cingulate: { m: "cingulado", f: "cingulada" },
  precuneal: { m: "precuneal", f: "precuneal" },
  paracentral: "paracentral",
  precentral: "precentral",
  postcentral: "poscentral",
  supramarginal: "supramarginal",
  angular: "angular",
  insular: "insular",
  frontal: "frontal",
  prefrontal: "prefrontal",
  frontobasal: "frontobasal",
  parietal: "parietal",
  occipital: "occipital",
  "temporo-occipital": "temporooccipital",
  temporal: "temporal",
  fusiform: "fusiforme",
  parahippocampal: "parahipocampal",
  orbital: "orbitaria",
  "supra-orbital": "supraorbitaria",
  supratrochlear: "supratroclear",
  infratrochlear: "infratroclear",
  trochlear: "troclear",
  optic: { m: "óptico", f: "óptica" },
  ophthalmic: { m: "oftálmico", f: "oftálmica" },
  oculomotor: { m: "oculomotor", f: "oculomotora" },
  nasociliary: { m: "nasociliar", f: "nasociliar" },
  ciliaris: "ciliar",
  ciliary: "ciliar",
  suspensory: { m: "suspensorio", f: "suspensoria" },
  vitreous: { m: "vítreo", f: "vítrea" },
  lacrimal: "lagrimal",
  nasolacrimal: "nasolagrimal",
  palpebrae: "del párpado",
  superioris: "superior",
  nasal: "nasal",
  ethmoidal: "etmoidal",
  alar: "alar",
  palatine: { m: "palatino", f: "palatina" },
  palatini: { m: "palatino", f: "palatina" },
  veli: "del velo",
  palatopharyngeus: "palatofaríngeo",
  pharyngeal: { m: "faríngeo", f: "faríngea" },
  salpingopharyngeus: "salpingofaríngeo",
  stylopharyngeus: "estilofaríngeo",
  constrictor: "constrictor",
  thyrohyoid: "tirohioideo",
  sternohyoid: "esternohioideo",
  sternothyroid: "esternotiroideo",
  omohyoid: "omohioideo",
  geniohyoid: "geniohioideo",
  mylohyoid: "milohioideo",
  stylohyoid: "estilohioideo",
  digastric: { m: "digástrico", f: "digástrica" },
  genioglossus: "geniogloso",
  hyoglossus: "hiogloso",
  sublingual: "sublingual",
  submandibular: "submandibular",
  pterygomandibular: "pterigomandibular",
  platysma: "platisma",
  sternocleidomastoid: "esternocleidomastoideo",
  scalenus: { m: "escaleno", f: "escalena" },
  cricothyroid: "cricotiroideo",
  "crico-arytenoid": "cricoaritenoideo",
  "thyro-arytenoid": "tiroaritenoideo",
  aryepiglotticus: "ariepiglótico",
  "hyo-epiglottic": "hioepiglótico",
  "thyro-epiglottic": "tiroepiglótico",
  corniculate: { m: "corniculado", f: "corniculada" },
  cuneiform: { m: "cuneiforme", f: "cuneiforme" },
  vocal: "vocal",
  vocalis: "vocal",
  uvular: "uvular",
  elasticus: { m: "elástico", f: "elástica" },
  zygomatic: { m: "cigomático", f: "cigomática" },
  xiphoid: { m: "xifoides", f: "xifoides" },

  // dentición
  molar: { m: "molar", f: "molar" },
  premolar: { m: "premolar", f: "premolar" },
  incisor: { m: "incisivo", f: "incisiva" },
  canine: { m: "canino", f: "canina" },
  alveolar: "alveolar",

  // músculos con nombre latino
  flexor: "flexor",
  extensor: "extensor",
  abductor: "abductor",
  adductor: "aductor",
  levator: "elevador",
  levatores: "elevadores",
  tensor: "tensor",
  pronator: "pronador",
  supinator: "supinador",
  rotator: "rotador",
  rectus: { m: "recto", f: "recta" },
  biceps: "bíceps",
  triceps: "tríceps",
  quadratus: { m: "cuadrado", f: "cuadrada" },
  teres: { m: "redondo", f: "redonda" },
  deltoid: { m: "deltoides", f: "deltoides" },
  trapezius: "trapecio",
  rhomboid: { m: "romboides", f: "romboides" },
  serratus: { m: "serrato", f: "serrata" },
  pectoralis: "pectoral",
  latissimus: { m: "ancho", f: "ancha" },
  infraspinatus: "infraespinoso",
  supraspinatus: "supraespinoso",
  subscapularis: "subescapular",
  coracobrachialis: "coracobraquial",
  brachialis: "braquial",
  brachioradialis: "braquiorradial",
  anconeus: { m: "ancóneo", f: "ancónea" },
  palmaris: "palmar",
  lumbrical: "lumbrical",
  lumbricals: "lumbricales",
  opponens: "oponente",
  gluteus: "glúteo",
  piriformis: "piriforme",
  gemellus: { m: "gémino", f: "gémina" },
  pectineus: { m: "pectíneo", f: "pectínea" },
  gracilis: "grácil",
  sartorius: "sartorio",
  semimembranosus: "semimembranoso",
  semitendinosus: "semitendinoso",
  vastus: { m: "vasto", f: "vasta" },
  lateralis: "lateral",
  medialis: "medial",
  psoas: "psoas",
  iliacus: { m: "ilíaco", f: "ilíaca" },
  iliotibial: "iliotibial",
  iliocostalis: "iliocostal",
  longissimus_m: "largo",
  spinalis: { m: "espinoso", f: "espinosa" },
  semispinalis: { m: "semiespinoso", f: "semiespinosa" },
  splenius: { m: "esplenio", f: "esplenia" },
  intertransversarius: "intertransverso",
  intertransversarii: "intertransversos",
  interspinales: "interespinosos",
  interspinalis: "interespinoso",
  levatorescostarum: "elevadores de las costillas",
  tibialis: "tibial",
  gastrocnemius: { m: "gastrocnemio", f: "gastrocnemia" },
  soleus: { m: "sóleo", f: "sólea" },
  plantaris: "plantar",
  popliteus: { m: "poplíteo", f: "poplítea" },
  fasciae: "de la fascia",
  latae: "lata",
  iliococcygeus: "iliococcígeo",
  pubococcygeus: "pubococcígeo",
  puborectalis: "puborrectal",
  ani: "del ano",
  transversalis: "transversal",
  alba: "alba",
  linea: "línea",
  cavernosum: { m: "cavernoso", f: "cavernosa" },
  spongiosum: { m: "esponjoso", f: "esponjosa" },
  deferent: "deferente",
  seminal: "seminal",
  tendinous: { m: "tendinoso", f: "tendinosa" },
  check: { m: "de contención", f: "de contención" },
  cava: { m: "cavo", f: "cava" },
  basilic: { m: "basílico", f: "basílica" },
  cephalic: { m: "cefálico", f: "cefálica" },
  caudate: { m: "caudado", f: "caudada" },
  intervertebral: "intervertebral",
  median: { m: "mediano", f: "mediana" },
  medius: { m: "medio", f: "media" },
  pedis: "del pie",
  spinal: "espinal",
  venous: { m: "venoso", f: "venosa" },
  arterial: { m: "arterial", f: "arterial" },
  conus: "cono",
  "with": "con",
  "to": "hacia",
};

/* ==========================================================================
   FRASES COMPLETAS · las estructuras que una docente busca por su nombre.
   Se aplican antes que cualquier regla, así que su traducción es exacta.
   ========================================================================== */
export const FRASES = {
  "heart": "Corazón",
  "brain": "Encéfalo",
  "liver": "Hígado",
  "spleen": "Bazo",
  "stomach": "Estómago",
  "pancreas": "Páncreas",
  "trachea": "Tráquea",
  "esophagus": "Esófago",
  "oesophagus": "Esófago",
  "tongue": "Lengua",
  "skin": "Piel",
  "diaphragm": "Diafragma",
  "rectum": "Recto",
  "duodenum": "Duodeno",
  "appendix": "Apéndice vermiforme",
  "urinary bladder": "Vejiga urinaria",
  "prostate": "Próstata",
  "thymus": "Timo",
  "epiglottis": "Epiglotis",
  "hyoid": "Hueso hioides",
  "sternum": "Esternón",
  "sacrum": "Sacro",
  "atlas": "Atlas (primera vértebra cervical)",
  "axis": "Axis (segunda vértebra cervical)",
  "vomer": "Vómer",
  "mandible": "Mandíbula",
  "linea alba": "Línea alba",
  "corpus callosum": "Cuerpo calloso",
  "medulla oblongata": "Bulbo raquídeo",
  "pons": "Puente de Varolio",
  "cerebellum": "Cerebelo",
  "thalamus": "Tálamo",
  "hypothalamus": "Hipotálamo",
  "hippocampus": "Hipocampo",
  "amygdala": "Amígdala cerebral",
  "putamen": "Putamen",
  "insula": "Ínsula",
  "midbrain": "Mesencéfalo",
  "forebrain": "Prosencéfalo",
  "telencephalon": "Telencéfalo",
  "pituitary gland": "Hipófisis",
  "pineal body": "Glándula pineal",
  "thyroid gland": "Glándula tiroides",
  "gingiva of upper jaw": "Encía del maxilar superior",
  "gingiva of lower jaw": "Encía de la mandíbula",
  "aorta": "Aorta",
  "vena cava": "Vena cava",
  "portal vein": "Vena porta",
  "azygos vein": "Vena ácigos",
  "gallbladder": "Vesícula biliar",
  "kidney": "Riñón",
  "ureter": "Uréter",
  "urethra": "Uretra",
  "spinal cord": "Médula espinal",
  "vertebral canal": "Conducto vertebral",
  "nasal septum": "Tabique nasal",
  "hard palate": "Paladar duro",
  "soft palate": "Paladar blando",
};

/* ==========================================================================
   DENTICIÓN · nomenclatura odontológica, que no sale de las reglas generales

   BodyParts3D escribe «Left lower first secondary molar tooth». En una
   consulta peruana eso es «Primer molar permanente inferior izquierdo»: el
   tipo de diente es el sustantivo y «tooth» desaparece. Merece regla propia
   porque es el vocabulario central del atlas maxilofacial.
   ========================================================================== */
export const TIPOS_DE_DIENTE = {
  molar: "molar",
  premolar: "premolar",
  incisor: "incisivo",
  canine: "canino",
};

export const ORDINAL_DIENTE = {
  first: "Primer",
  second: "Segundo",
  third: "Tercer",
};
